spring:
  jmx:
    enabled: false
  datasource:
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL}
      security.protocol: SSL
      ssl.truststore.type: PKCS12
      ssl.truststore.location: /cert/truststore.p12
      ssl.truststore.password: ${TRUSTSTORE_PASSWORD}
      ssl.keystore.type: PKCS12
      ssl.keystore.location: /cert/keystore.p12
      ssl.keystore.password: ${KEYSTORE_PASSWORD}
      ssl.key.password: ${KEYSTORE_PASSWORD}
      schema.registry.ssl.truststore.type: PKCS12
      schema.registry.ssl.truststore.location: /cert/truststore.p12
      schema.registry.ssl.truststore.password: ${TRUSTSTORE_PASSWORD}
      schema.registry.ssl.keystore.type: PKCS12
      schema.registry.ssl.keystore.location: /cert/keystore.p12
      schema.registry.ssl.keystore.password: ${KEYSTORE_PASSWORD}
    consumer:
      fetch-max-bytes: 2048576
      max-partition-fetch-bytes: 262144
      group-id: vectorization-worker-consumer-group
  cloud:
    gcp:
      sql:
        database-name: ${PROD_DB_NAME}
        instance-connection-name: ${GCP_SQL_INSTANCE_CONNECTION_NAME}
management:
  metrics:
    enable:
      kafka: false